name: Build Branch

on:
  push:
    branches-ignore: [ forge-1.12.2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build jar
        run: ./gradlew build
      - name: Build dev jar
        run: ./gradlew devJar
      - name: Build api jar
        run: ./gradlew apiJar
