name: Build Master

on:
  push:
    branches: [ forge-1.12.2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUMP_VERSION: true
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout Tags # Work around https://github.com/actions/checkout/issues/290
      run: git fetch --force --tags
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build jar
      run: ./gradlew build
    - name: Build dev jar
      run: ./gradlew devJar
    - name: Build api jar
      run: ./gradlew apiJar
    - name: Upload maven package
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
